### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by webmasterMeyers** [php-translation/flysystem-adapter#6]
This is more of a heads up, but I just fought with this configuration for almost a week, getting all sorts of permission errors.  Can not crrate folder ....

Turns out the solution was that I needed to start `path:` with a `/` This would give me errors

````
translation_adapter_flysystem:
  filesystems:
    s3:
      flysystem_service: 'oneup_flysystem.asset_storage_fs_filesystem'
      path: 'Translations'
````

This works!
````
translation_adapter_flysystem:
  filesystems:
    s3:
      flysystem_service: 'oneup_flysystem.asset_storage_fs_filesystem'
      path: '/Translations'
````
